### ISSUE TITLE
Analytics packages depend on postgresql-contrib-10

### ISSUE THREAD

**Issue by furkansahin** [citusdata/packaging#218]
Session analytics debian packages has a dependency on postgresql-contrib-10. Actually, it doesn't check the pg version. So, no matter the version, dependency is added there. However, postgresql does not publish contrib packages anymore (>=10.0). 

This makes the package to not being installed since `apt-get install postgresql-10-citus-analytics_10-1.0.0....` will look for that package and if it is not there, it will try to install the `contrib` package, but the package does not exist, so the installation will fail.

If we decide on not supporting session-analytics anymore, we should simply omit this issue. I have never heard that this package is used. It seems like session-analytics is mainly created for the cases that we did not support previously. Shall we degrade this package?

**Comment by DimCitus** [comment]
In case this might be helpful: the current packages for PostgreSQL 10 and PostgreSQL 11 contain the contrib extensions, that's why there's no longer a separate package for them in debian.

  https://packages.debian.org/sid/amd64/postgresql-10/filelist
  https://packages.debian.org/sid/amd64/postgresql-11/filelist

Also you can see on the PostgreSQL-10 and PostgreSQL-11 debian packages that they still do provide the compatibility contrib debian package, which means you can still depend on the binary package `postgresql-contrib-10` from your package.

  https://salsa.debian.org/postgresql/postgresql/blob/10/debian/control
  https://salsa.debian.org/postgresql/postgresql/blob/11/debian/control

Both have a _Provides_ section with the relevant contrib package, here for PostgreSQL 10:

```
Provides: postgresql-contrib-10
```

So it should be good on that front. 

Now, you can use `pg_buildext` to solve those dependencies for you automatically at debian package build time and using a `control.in` file in the source repository, that will be rewritten as a `control` file publishing many binary packages from the same source package. That's what the `prefix` package is using, for instance. That allows having a separate binary package of session-analytics for each supported PostgreSQL version available in debian.

  https://manpages.debian.org/jessie/postgresql-server-dev-all/pg_buildext.1.en.html
  https://github.com/dimitri/prefix/blob/master/debian/control.in

HTH

**Comment by jasonmp85** [comment]
@DimCitus this _should_ be how it's set up already. I'm admittedly kind of out of the loop on the session analytics question, but we use `pg_buildext` to build packages for all our debian packages.

**Comment by hanefi** [comment]
We stopped maintaining session analytics and creating packages for it
