### ISSUE TITLE
Changes on packaging repo is not being tracked while deciding package change

### ISSUE THREAD

**Issue by gurkanindibay** [citusdata/packaging#607]
While releasing packages on packagecloud, a control is being made to check whether there is code change after last package push. While checking changes, only the main repository including application codes are being checked. However, there are come config files on packaging repo that changes on these files should trigger new build. 
Changes on packaging repo should be tracked to decide whether package is new or not

**Comment by hanefi** [comment]
I do not agree with this, and want to make some corrections.

> While checking changes, only the main repository including application codes are being checked.

This is not entirely true. We check if there exists a package with the same name that we wish to create. It is correct that the package name contains the tag in it, but we also have fancy versioning. This means that using a different tag on the project repository, or bumping the fancy version in the packaging repository branch creates a unique name that will not collide with the existing packages on PackageCloud.

I think we should not update the packages due to changes on packaging branch. If this is really needed, we need to bump the fancy version to create and publish new sets of packages.

**Comment by gurkanindibay** [comment]
I agree with @hanefi it is not needed right now
